const FAVORITE_BOOKS = {
    ADD: 'FAVORITE_BOOKS_ADD',
    REMOVE: 'FAVORITE_BOOKS_REMOVE',
    GET_REQUESTED: 'FAVORITE_BOOKS_GET_REQUESTED',
    GET_SUCCEEDED: 'FAVORITE_BOOKS_GET_SUCCEEDED',
    GET_FAILED: 'FAVORITE_BOOKS_GET_FAILED'
}

export { FAVORITE_BOOKS as default }