const BOOKS = {
    GET_REQUESTED: 'BOOKS_GET_REQUESTED',
    GET_SUCCEEDED: 'BOOKS_GET_SUCCEEDED',
    GET_FAILED: 'BOOKS_GET_FAILED',
    SET_ORDER_BY: 'BOOKS_SET_ORDER_BY',
    SET_SEARCH_TERM: 'BOOKS_SET_SEARCH_TERM',
    SET_VIEW: 'BOOKS_SET_VIEW'
}

export { BOOKS as default }